BEGIN TRANSACTION;

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_USER TEXT NOT NULL,
    USER_PASSWORD TEXT NOT NULL
);

INSERT INTO USERS (USER_USER, USER_PASSWORD)
    VALUES
    ('admin','1234');


COMMIT;