-- Create foreign key PRODUTOS_FK

CREATE TEMPORARY TABLE temp AS
SELECT *
FROM PRODUTOS;

DROP TABLE PRODUTOS;

CREATE TABLE PRODUTOS (
	PRODUTO_CODIGO INTEGER PRIMARY KEY AUTOINCREMENT,
	PRODUTO_NOME TEXT NOT NULL,
	PRATELEIRA_ID INTEGER,
	PRODUTO_QUANTIDADE INTEGER,
	PRODUTO_VALOR_UN FLOAT DEFAULT '0' NOT NULL,
	CONSTRAINT PRODUTOS_FK FOREIGN KEY (PRATELEIRA_ID) REFERENCES PRATELEIRAS(PRATELEIRA_CODIGO) ON DELETE RESTRICT
);

INSERT INTO PRODUTOS
SELECT *
FROM temp;

DROP TABLE temp;


-- Create foreign key ITENS_CUPOM_FISCAL_FK

CREATE TEMPORARY TABLE temp AS
SELECT *
FROM ITENS_CUPOM_FISCAL;

DROP TABLE ITENS_CUPOM_FISCAL;

CREATE TABLE ITENS_CUPOM_FISCAL (
	ITEN_CUPOM_FISCAL_CODIGO INTEGER PRIMARY KEY AUTOINCREMENT,
	ITEN_CUPOM_FISCAL_NUMERO INTEGER,
	ITEN_CUPOM_FISCAL_SEQUENCIA INTEGER NOT NULL,
	ITEN_CUPOM_FISCAL_PRODUTO INTEGER NOT NULL,
	ITEN_CUPOM_FISCAL_QUANTIDADE FLOAT NOT NULL,
	ITEN_CUPOM_FISCAL_VALOR_UN FLOAT DEFAULT '0' NOT NULL,
	ITEN_CUPOM_FISCAL_VALOR_TOT FLOAT DEFAULT '0' NOT NULL,
	CONSTRAINT ITENS_CUPOM_FISCAL_FK FOREIGN KEY (ITEN_CUPOM_FISCAL_NUMERO) REFERENCES NOTAS(NOTA_ID) ON DELETE RESTRICT
);

INSERT INTO ITENS_CUPOM_FISCAL
SELECT *
FROM temp;

DROP TABLE temp;

-- Create foreign key NOTAS_FK

CREATE TEMPORARY TABLE temp AS
SELECT *
FROM NOTAS;

DROP TABLE NOTAS;

CREATE TABLE NOTAS (
	NOTA_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	NOTA_DATA_DE_EMISSAO TEXT NOT NULL,
	NOTA_CLIENTE INTEGER NOT NULL,
	NOTA_ATENDENTE INTEGER NOT NULL,
	CONSTRAINT NOTAS_FK FOREIGN KEY (NOTA_CLIENTE) REFERENCES CLIENTES(CLIENTE_CODIGO) ON DELETE RESTRICT,
	CONSTRAINT NOTAS_FK_1 FOREIGN KEY (NOTA_ATENDENTE) REFERENCES ATENDENTES(ATENDENTE_CODIGO) ON DELETE RESTRICT
);

INSERT INTO NOTAS
SELECT *
FROM temp;

DROP TABLE temp;
-- Create foreign key NOTAS_FK_1

CREATE TEMPORARY TABLE temp AS
SELECT *
FROM NOTAS;

DROP TABLE NOTAS;

CREATE TABLE NOTAS (
	NOTA_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	NOTA_DATA_DE_EMISSAO TEXT NOT NULL,
	NOTA_CLIENTE INTEGER NOT NULL,
	NOTA_ATENDENTE INTEGER NOT NULL,
	CONSTRAINT NOTAS_FK FOREIGN KEY (NOTA_CLIENTE) REFERENCES CLIENTES(CLIENTE_CODIGO) ON DELETE RESTRICT,
	CONSTRAINT NOTAS_FK_1 FOREIGN KEY (NOTA_ATENDENTE) REFERENCES ATENDENTES(ATENDENTE_CODIGO) ON DELETE RESTRICT
);

INSERT INTO NOTAS
SELECT *
FROM temp;

DROP TABLE temp;


-- Create foreign key CLIENTES_FK

CREATE TEMPORARY TABLE temp AS
SELECT *
FROM CLIENTES;

DROP TABLE CLIENTES;

CREATE TABLE CLIENTES (
	CLIENTE_CODIGO INTEGER PRIMARY KEY AUTOINCREMENT,
	CLIENTE_NOME TEXT NOT NULL,
	CLIENTE_TELEFONE INTEGER NOT NULL,
	CLIENTE_CPF INTEGER NOT NULL,
	CLIENTE_TOTAL_COMPRAS INTEGER NOT NULL,
	CLIENTE_CIDADE_ID INTEGER ,
	CONSTRAINT CLIENTES_FK FOREIGN KEY (CLIENTE_CIDADE_ID) REFERENCES CIDADES(CIDADE_ID) ON DELETE RESTRICT
);

INSERT INTO CLIENTES
SELECT *
FROM temp;

DROP TABLE temp;


-- Create foreign key ITENS_CUPOM_FISCAL_FK_1

CREATE TEMPORARY TABLE temp AS
SELECT *
FROM ITENS_CUPOM_FISCAL;

DROP TABLE ITENS_CUPOM_FISCAL;

CREATE TABLE ITENS_CUPOM_FISCAL (
	ITEN_CUPOM_FISCAL_CODIGO INTEGER PRIMARY KEY AUTOINCREMENT,
	ITEN_CUPOM_FISCAL_NUMERO INTEGER,
	ITEN_CUPOM_FISCAL_SEQUENCIA INTEGER NOT NULL,
	ITEN_CUPOM_FISCAL_PRODUTO INTEGER NOT NULL,
	ITEN_CUPOM_FISCAL_QUANTIDADE FLOAT NOT NULL,
	ITEN_CUPOM_FISCAL_VALOR_UN FLOAT DEFAULT '0' NOT NULL,
	ITEN_CUPOM_FISCAL_VALOR_TOT FLOAT DEFAULT '0' NOT NULL,
	CONSTRAINT ITENS_CUPOM_FISCAL_FK FOREIGN KEY (ITEN_CUPOM_FISCAL_NUMERO) REFERENCES NOTAS(NOTA_ID) ON DELETE RESTRICT,
	CONSTRAINT ITENS_CUPOM_FISCAL_FK_1 FOREIGN KEY (ITEN_CUPOM_FISCAL_PRODUTO) REFERENCES PRODUTOS(PRODUTO_CODIGO)
);

INSERT INTO ITENS_CUPOM_FISCAL
SELECT *
FROM temp;

DROP TABLE temp;

