
-- SELECT * FROM PESSOAS;

-- SELECT * FROM CIDADES;

-- SELECT PESSOAS_NOME FROM PESSOAS;

-- SELECT DISTINCT (PESSOAS_NOME)
-- FROM PESSOAS;

-- SELECT PESSOAS_NOME FROM PESSOAS 
-- WHERE PESSOAS_IDADE < 20;

-- SELECT * FROM PESSOAS WHERE PESSOAS_IDADE IN (20,40);

-- SELECT * FROM PESSOAS WHERE PESSOAS_IDADE IN (20,40);
-- SELECT * FROM PESSOAS WHERE PESSOAS_NOME LIKE '%Thiag%';
-- SELECT * FROM PESSOAS WHERE PESSOAS_NOME LIKE '%Thiag%' AND PESSOAS_IDADE = 21;
-- SELECT * FROM PESSOAS WHERE PESSOAS_NOME LIKE '%Thiag%' OR PESSOAS_NOME LIKE '%Joa%';
-- SELECT * FROM PESSOAS WHERE PESSOAS_IDADE BETWEEN 20 AND 25;


-- select avg(pessoa_idade) from pessoas; 

-- select min(pessoa_idade) from pessoas; 

-- select max(pessoa_idade) from pessoas;

-- select sum(pessoa_idade) from pessoas;

-- select count(*) from pessoas; 


-- SELECT PESSOAS_IDADE, COUNT(PESSOAS_NOME) FROM PESSOAS GROUP BY PESSOAS_IDADE;


-- SELECT 
--     CIDADES.CIDADES_NOME, 
--     PESSOAS.PESSOAS_NOME,
--     PESSOAS.PESSOAS_IDADE
-- FROM    
--     PESSOAS,CIDADES
-- WHERE 
--     PESSOAS.PESSOAS_CIDADES_ID = CIDADES.CIDADES_ID;